### ISSUE TITLE
Multiple handzones cause low FPS

### ISSUE THREAD

**Issue by Skeeve2** [tts-community/tts-community-bug-tracker#1]
**Describe the bug**
Multiple handzones for players cause FPS issues

**To Reproduce**
1. Create 6-8 handzones
2. Place multiple cards into hand zones

**Expected behavior**
FPS should not be affected by multiple handzones

**Screenshots**
N/A

**Lua Scripts & XML UI**:
N/A

If applicable, XML:
N/A

**Tabletop Simulator Info (please complete the following information):**
 - OS: Windows 10.0.18362 Build 18362
- Processor: AMD Ryzen 5 2600 Six-Core Processor, 3400 Mhz, 6 Core(s), 12 Logical Processor(s)
- Total Physical Memory	16.0 GB
 - Version:  v12.1.6

**Additional context**
Sample Mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1163357849
Original report: http://www.berserk-games.com/forums/showthread.php?8096-Cards-lagging-when-in-player-s-hands

**Comment by jojoxd** [comment]
experiencing the same issue;

* OS: Windows 10 1903 Build 18362.657
* CPU: 2x E5-2620v4
* RAM: 32GB
* GPU: Zotac GeForece GTX 1060 AMP!/Mini

**Comment by Skeeve2** [comment]
Fixed in 12.4.0
